    /*
 * The MIT License
 *
 * Copyright 2019 Ing Dexus José Pérez <joser_perezmiranda@gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package MenuPrincipal.login;

import MenuPrincipal.pathVerificacion;
import MenuPrincipal.principal;
import java.awt.Window;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ing Dexus José Pérez <joser_perezmiranda@gmail.com>
 */
public class panelUser extends javax.swing.JPanel {

    /**
     * Creates new form panelUser
     */
    public panelUser() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_Acceso = new javax.swing.JButton();
        tf_Usuario = new javax.swing.JTextField();
        tf_pass = new javax.swing.JPasswordField();
        bt_Salir = new javax.swing.JButton();

        setBackground(MenuPrincipal.principal.Fond_blue);
        setPreferredSize(new java.awt.Dimension(300, 200));

        jLabel1.setFont(MenuPrincipal.principal.ArialB14);
        jLabel1.setText("Usuario:");

        jLabel2.setFont(MenuPrincipal.principal.ArialB14);
        jLabel2.setText("Contraseña:");

        bt_Acceso.setFont(MenuPrincipal.principal.ArialB14);
        bt_Acceso.setText("Ingresar");
        bt_Acceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AccesoActionPerformed(evt);
            }
        });

        tf_Usuario.setFont(MenuPrincipal.principal.ArialB14);
        tf_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Usuario.setPreferredSize(new java.awt.Dimension(120, 30));

        tf_pass.setFont(MenuPrincipal.principal.ArialB14);
        tf_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_pass.setPreferredSize(new java.awt.Dimension(120, 30));

        bt_Salir.setFont(MenuPrincipal.principal.ArialB14);
        bt_Salir.setText("Salir");
        bt_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_Acceso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Acceso)
                    .addComponent(bt_Salir))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AccesoActionPerformed
        
        //System.out.println(tf_Usuario.getText()+Arrays.toString(tf_pass.getPassword()));
        
        String pass = new String(tf_pass.getPassword());
        String user = tf_Usuario.getText();
        
        pathVerificacion veri = new pathVerificacion();
        
        try {
            veri.defaultProperties.load(new FileReader(veri.Propertie.toString()));
            
            if(veri.defaultProperties.getProperty("user", "default value").equals(user) && veri.defaultProperties.getProperty("pass", "default value").equals(pass)){
                JOptionPane.showMessageDialog(this, "acceso correcto");
                
                try {
                   principal.principal.setEnabled(true); 
                } catch (Exception e) {
                }
                
                
                
                Window win = SwingUtilities.getWindowAncestor(this);
                
                win.dispose();
                
            }else{
                JOptionPane.showMessageDialog(this, "usuario o contraseña incorrecta");
            }
            
            //veri.defaultFile.close();
            
            
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        System.out.println(user);
        System.out.println(pass);
        
    }//GEN-LAST:event_bt_AccesoActionPerformed

    private void bt_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SalirActionPerformed
        new principal().cerrarPrograma();
    }//GEN-LAST:event_bt_SalirActionPerformed

    
    public boolean confirmado(){
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Acceso;
    private javax.swing.JButton bt_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tf_Usuario;
    private javax.swing.JPasswordField tf_pass;
    // End of variables declaration//GEN-END:variables
}
